### ISSUE TITLE
Payment methods do not honor zone setting

### ISSUE THREAD

**Issue by Zen4All** [lat9/one_page_checkout#153] opened 2018-11-14 20:51 UTC
When multiple payment methods are present, and some have a zone restricting the method to a certain country, or region.
In a stock Zen Cart installation these settings are correctly used, but OPC shows all payment methods regards the billing country, or the zone setting of the methods.

**Comment by Zen4All** [comment] 2018-11-14 20:59
OPC payment screen
![opc_payment](https://user-images.githubusercontent.com/2766593/48511937-6d1a3400-e858-11e8-9b34-434b3927976f.jpg)
Standard checkout
![standard_payment](https://user-images.githubusercontent.com/2766593/48511946-6f7c8e00-e858-11e8-98f0-84e3005baa13.jpg)

**Comment by lat9** [comment] 2018-11-15 11:09
Thanks for the report, @Zen4All, I'll see what is going on.

**Comment by lat9** [comment] 2018-11-15 11:56
I'm not able to reproduce.  Here's what I've done (zc155f, opc 2.0.4, responsive_classic template).

Set 'cod' method to activate only for Mexico.  Store's default address (and thus the Guest default) is USA/FL.

Add product to cart, go to guest checkout.  'cod' method doesn't show (since the guest default is US-based).  Entered address as Mexico-based; on saving the address, the 'cod' payment method now shows.

Since that's not what you're seeing, there's some difference in configuration that's the basis of the issue.  Any/all information you can provide will help ... I can't correct what I can't see.

**Comment by Zen4All** [comment] 2018-11-15 12:14
If you want you can look on the site from the previous issue, and use the known details to login. I'll send you admin details for the backend

**Comment by Zen4All** [comment] 2018-11-15 15:23
I did not test for the standard payment method with different zones. They work fine, so it must be something in the sisow modules.
I am going to figure this out on my own, as I now suspect it is not an OPC problem.
I'll let you know my findings, thanks for helping so far

---

**Comment by lat9** [comment] 2018-11-16 12:33
I'll hold this issue open for a bit, while you verify that it's not an OPC problem.

**Comment by lat9** [comment] 2019-03-12 12:53
FWIW, I've verified that this is non-issue for OPC 2.1.0-beta5.

**Comment by lat9** [comment] 2024-01-13 15:28
Closing as not reproducible.

**Closed by lat9** 2024-01-13 15:28 UTC
Labels: not reproducible, question, interoperation
